In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
cancer = pd.read_csv('cancer.csv')

In [3]:
 = cancer.drop(['Class'],axis=1)

In [4]:
y = cancer['Class']

In [5]:
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X)

#Computing the covariance matrix

In [12]:
import numpy as np

# Compute the mean of the data
mean_vec = np.mean(X, axis=0)

print("mean_vec \n")
print(mean_vec)
print("\n")

# Compute the covariance matrix
cov_mat = (X - mean_vec).T.dot((X - mean_vec)) / (X.shape[0]-1)

print("cov_mat \n")
print(cov_mat)
print("\n")

# OR we can do this with one line of numpy:
cov_mat = np.cov(X.T)

print("cov_mat \n")
print(cov_mat)

mean_vec 

[-1.37363271e-16  6.86816353e-17 -1.24875700e-16 -2.18532476e-16
  1.74825981e-16  1.99801121e-16  1.24875700e-16 -3.74627101e-17
  1.87313551e-16  4.52674414e-16  2.49751401e-16 -1.03022453e-16
 -3.49651961e-16 -1.31119486e-16  4.40186844e-16  1.81069766e-16
 -1.24875700e-17  1.24875700e-17  8.11692053e-17 -3.74627101e-17
 -8.24179623e-16  1.24875700e-17 -3.74627101e-16  0.00000000e+00
 -2.37263831e-16 -3.37164391e-16  7.49254203e-17  2.24776261e-16
  2.74726541e-16  2.12288691e-16]


cov_mat 

[[ 1.00176056e+00  3.24351929e-01  9.99612069e-01  9.89095475e-01
   1.70881506e-01  5.07014640e-01  6.77955035e-01  8.23976636e-01
   1.48001350e-01 -3.12179472e-01  6.80285970e-01 -9.74887767e-02
   6.75358538e-01  7.37159198e-01 -2.22992026e-01  2.06362656e-01
   1.94545518e-01  3.76831225e-01 -1.04504545e-01 -4.27161775e-02
   9.71245907e-01  2.97530545e-01  9.66835698e-01  9.42739295e-01
   1.19826732e-01  4.14190751e-01  5.27839123e-01  7.45524434e-01
   1.64241985e-01  7.07832

#Computing Eigen Values and Vectors

In [14]:
# Compute the eigen values and vectors using numpy
eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print("eig_vals \n")
print(eig_vals)
print("\n")

print("eig_vecs \n")
print(eig_vecs)
print("\n")
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort(key=lambda x: x[0], reverse=True)

print("eig_pairs \n")
print(eig_pairs)

eig_vals 

[1.33049910e+01 5.70137469e+00 2.82291007e+00 1.98412752e+00
 1.65163308e+00 1.20948226e+00 6.76408819e-01 4.77456254e-01
 4.17628770e-01 3.51310854e-01 2.94433167e-01 2.61621103e-01
 2.41782513e-01 1.57286166e-01 9.43006891e-02 8.00034014e-02
 5.95036100e-02 5.27114242e-02 4.95647015e-02 1.33279055e-04
 7.50121432e-04 1.59213592e-03 6.91261229e-03 8.19203811e-03
 1.55085245e-02 1.80867937e-02 2.43836831e-02 2.74877346e-02
 3.12142553e-02 3.00256631e-02]


eig_vecs 

[[ 2.18902439e-01 -2.33857137e-01 -8.53125261e-03  4.14089762e-02
  -3.77863323e-02  1.87407820e-02  1.24088391e-01  7.45234243e-03
  -2.23109709e-01  9.54864661e-02  4.14714685e-02  5.10675763e-02
   1.19674252e-02 -5.95060959e-02  5.11188791e-02 -1.50583805e-01
   2.02924297e-01  1.46712166e-01 -2.25384736e-01 -7.02414093e-01
   2.11460459e-01 -2.11193995e-01 -1.31526621e-01  1.29476422e-01
   1.92263087e-02 -1.82579544e-01  9.85526055e-02 -7.29292251e-02
  -4.96984139e-02  6.85698770e-02]
 [ 1.03724575e-01 -5

#Choose the first K eigenvalues (K principal components/axises):

In [16]:
totalSum = sum(eig_vals)
variablesExplained = [(i / totalSum) for i in sorted(eig_vals, reverse = True)]
print(variablesExplained)

[0.44272026158799466, 0.18971182341480106, 0.09393162965420133, 0.06602134936583531, 0.05495767956877253, 0.040245221131488415, 0.022507335052199054, 0.01588723798446043, 0.013896493352142193, 0.01168978119741538, 0.009797190320729603, 0.008705377055605576, 0.008045252915671318, 0.005233658020566204, 0.0031378319527075225, 0.002662093263128736, 0.001979967806576399, 0.0017539595175141843, 0.001649253103413267, 0.0010386465734580708, 0.0009990964632306234, 0.0009146475267037064, 0.000811360985021783, 0.0006018335568116827, 0.0005160422906320963, 0.00027258802835830126, 0.0002300154529580767, 5.297792633622849e-05, 2.4960103892642158e-05, 4.434827373651716e-06]


In [17]:
featureVector = eig_vecs[:,:2]
print(featureVector)

[[ 0.21890244 -0.23385714]
 [ 0.10372457 -0.0597061 ]
 [ 0.22753729 -0.21518137]
 [ 0.22099498 -0.23107672]
 [ 0.1425897   0.18611303]
 [ 0.23928535  0.1518916 ]
 [ 0.25840048  0.06016535]
 [ 0.26085376 -0.03476751]
 [ 0.13816696  0.19034877]
 [ 0.06436335  0.36657546]
 [ 0.20597877 -0.10555216]
 [ 0.01742803  0.08997968]
 [ 0.21132591 -0.08945724]
 [ 0.20286963 -0.15229264]
 [ 0.01453146  0.20443046]
 [ 0.17039345  0.23271588]
 [ 0.15358979  0.19720727]
 [ 0.1834174   0.13032155]
 [ 0.04249842  0.18384799]
 [ 0.10256839  0.28009204]
 [ 0.22799663 -0.21986638]
 [ 0.10446932 -0.04546731]
 [ 0.23663968 -0.19987843]
 [ 0.22487053 -0.21935186]
 [ 0.12795256  0.17230436]
 [ 0.21009588  0.14359316]
 [ 0.22876753  0.0979641 ]
 [ 0.25088597 -0.00825724]
 [ 0.12290456  0.14188335]
 [ 0.13178395  0.27533946]]


#Build the new reduced dataset:

In [19]:
featureVectorTranspose = np.transpose(featureVector)
datasetTranspose = np.transpose(X)
newDatasetTranspose = np.matmul(featureVectorTranspose, datasetTranspose)
newDataset = np.transpose(newDatasetTranspose)

In [20]:
newDataset

array([[ 9.19283686,  1.94858281],
       [ 2.38780174, -3.76817173],
       [ 5.73389626, -1.07517393],
       ...,
       [ 1.25617925, -1.90229676],
       [10.37479407,  1.67200972],
       [-5.47524329, -0.67063663]])

#Projection onto new vectors

In [8]:
# Only keep a certain number of eigen vectors based on 
# the "explained variance percentage" which tells us how 
# much information (variance) can be attributed to each 
# of the principal components

exp_var_percentage = 0.97 # Threshold of 97% explained variance

tot = sum(eig_vals)
var_exp = [(i / tot)*100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)

num_vec_to_keep = 0

for index, percentage in enumerate(cum_var_exp):
  if percentage > exp_var_percentage:
    num_vec_to_keep = index + 1
    break

In [9]:
# Compute the projection matrix based on the top eigen vectors
num_features = X.shape[1]
proj_mat = eig_pairs[0][1].reshape(num_features,1)
for eig_vec_idx in range(1, num_vec_to_keep):
  proj_mat = np.hstack((proj_mat, eig_pairs[eig_vec_idx][1].reshape(num_features,1)))

# Project the data 
pca_data = X.dot(proj_mat)

In [10]:
pca_data

array([[ 9.19283686],
       [ 2.38780174],
       [ 5.73389626],
       [ 7.12295342],
       [ 3.93530207],
       [ 2.38024723],
       [ 2.23888324],
       [ 2.14329857],
       [ 3.17492433],
       [ 6.35174698],
       [-0.81041381],
       [ 2.65110048],
       [ 8.18503463],
       [ 0.3421259 ],
       [ 4.34237933],
       [ 4.07565623],
       [ 0.23005497],
       [ 4.41801093],
       [ 4.94870344],
       [-1.23706336],
       [-1.57816123],
       [-3.55733632],
       [ 4.73321083],
       [ 4.20852409],
       [ 4.94963202],
       [ 7.09856293],
       [ 3.51026262],
       [ 3.06405387],
       [ 4.00726412],
       [ 1.71530971],
       [ 6.05944549],
       [ 2.90223619],
       [ 4.55478268],
       [ 4.99060268],
       [ 2.98534079],
       [ 2.76636912],
       [ 1.29619878],
       [-3.74931341],
       [-0.99806896],
       [ 0.76526413],
       [-2.15095352],
       [-0.09333135],
       [ 9.08799973],
       [ 0.99045378],
       [-0.29354658],
       [ 5